export const countries = [
    'afghanistan',
    'albania',
    'algeria',
    'andorra',
    'angola',
    'antigua and barbuda',
    'argentina',
    'armenia',
    'australia',
    'austria',
    'azerbaijan',
    'the bahamas',
    'bahrain',
    'bangladesh',
    'barbados',
    'belarus',
    'belgium',
    'belize',
    'benin',
    'bhutan',
    'bolivia',
    'bosnia and herzegovina',
    'botswana',
    'brazil',
    'brunei',
    'bulgaria',
    'burkina faso',
    'burundi',
    'cabo verde',
    'cambodia',
    'cameroon',
    'canada',
    'central african republic',
    'chad',
    'chile',
    'china',
    'colombia',
    'comoros',
    'congo, democratic republic of the',
    'congo, republic of the',
    'costa rica',
    'côte d’ivoire',
    'croatia',
    'cuba',
    'cyprus',
    'czech republic',
    'denmark',
    'djibouti',
    'dominica',
    'dominican republic',
    'east timor',
    'timor-leste',
    'ecuador',
    'egypt',
    'el salvador',
    'equatorial guinea',
    'eritrea',
    'estonia',
    'eswatini',
    'ethiopia',
    'fiji',
    'finland',
    'france',
    'gabon',
    'the gambia',
    'georgia',
    'germany',
    'ghana',
    'greece',
    'grenada',
    'guatemala',
    'guinea',
    'guinea-bissau',
    'guyana',
    'haiti',
    'honduras',
    'hungary',
    'iceland',
    'india',
    'indonesia',
    'iran',
    'iraq',
    'ireland',
    'israel',
    'italy',
    'jamaica',
    'japan',
    'jordan',
    'kazakhstan',
    'kenya',
    'kiribati',
    'north korea',
    'south korea',
    'korea',
    'kosovo',
    'kuwait',
    'kyrgyzstan',
    'laos',
    'latvia',
    'lebanon',
    'lesotho',
    'liberia',
    'libya',
    'liechtenstein',
    'lithuania',
    'luxembourg',
    'madagascar',
    'malawi',
    'malaysia',
    'maldives',
    'mali',
    'malta',
    'marshall islands',
    'mauritania',
    'mauritius',
    'mexico',
    'micronesia',
    'moldova',
    'monaco',
    'mongolia',
    'montenegro',
    'morocco',
    'mozambique',
    'myanmar',
    'namibia',
    'nauru',
    'nepal',
    'netherlands',
    'new zealand',
    'nicaragua',
    'niger',
    'nigeria',
    'north macedonia',
    'norway',
    'oman',
    'pakistan',
    'palau',
    'panama',
    'papua new guinea',
    'paraguay',
    'peru',
    'philippines',
    'poland',
    'portugal',
    'qatar',
    'romania',
    'russia',
    'rwanda',
    'saint kitts and nevis',
    'saint lucia',
    'saint vincent and the grenadines',
    'samoa',
    'san marino',
    'sao tome and principe',
    'saudi arabia',
    'senegal',
    'serbia',
    'seychelles',
    'sierra leone',
    'singapore',
    'slovakia',
    'slovenia',
    'solomon islands',
    'somalia',
    'south africa',
    'spain',
    'sri lanka',
    'sudan',
    'sudan, south',
    'suriname',
    'sweden',
    'switzerland',
    'syria',
    'tajikistan',
    'tanzania',
    'thailand',
    'togo',
    'tonga',
    'trinidad and tobago',
    'tunisia',
    'turkey',
    'turkmenistan',
    'tuvalu',
    'uganda',
    'ukraine',
    'united arab emirates',
    'united kingdom',
    'united states',
    'uruguay',
    'uzbekistan',
    'vanuatu',
    'vatican city',
    'venezuela',
    'vietnam',
    'yemen',
    'zambia',
    'zimbabwe'
];

export const altCountries = [
    'usa',
    'america',
    'great britain',
    'britain',
    'uk',
    'vatican',
    'korea',
];

export const oldCountries = [
    'persia',
    'burma',
    'abyssinia',
    'austria-hungary',
    'bengal',
    'corsica',
    'colombia grande',
    'granada',
    'prussia',
    'ottoman empire',
    'ottoman',
    'england',
    'scotland',
    'wales',
    'taiwan',
    'texas',
    'tibet',
    'ussr',
    'soviet union',
    'united arab republic',
    'uar',
    'mesopotamia'
];